# Generated by Django 3.2 on 2021-12-13 00:57

from django.db import migrations, models


def fill_initial_data(apps, schema_editor):
    Currency = apps.get_model('currencies', 'Currency')
    currencies = [
        {'name': 'US Dollar', 'code': 'USD'},
        {'name': 'Euro', 'code': 'EUR', 'base_currency': True, 'conversion_rate': 1.0},
        {'name': 'Egyptian Pound', 'code': 'EGP'},
    ]
    for curr in currencies:
        if not Currency.objects.filter(code=curr['code']).exists():
            Currency.objects.create(**curr)

    try:
        from currencies.tasks import update_exchange_rates
        update_exchange_rates()
    except:
        pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=4, unique=True)),
                ('conversion_rate', models.DecimalField(decimal_places=5, default=0.0, help_text='Rate should equal 1 for base currency', max_digits=8)),
                ('base_currency', models.BooleanField(default=False)),
            ],
        ),
         migrations.RunPython(fill_initial_data, reverse_code=migrations.RunPython.noop),
    ]
